name: Build Linux
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cmake
          cmake --version
      - name: Build hello example
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./BananaEmulator ../../tests/slug_files/hello_world1.slug
          ./BananaEmulator ../../tests/slug_files/hello_world2.slug
          ./BananaEmulator ../../tests/slug_files/hello_world3.slug < ../../tests/slug_files/hello_world1_input.txt